; PlatformIO Project Configuration File

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps =
	adafruit/Adafruit ICM20X@^2.0.5
	adafruit/Adafruit BusIO@^1.14.1
	adafruit/Adafruit Unified Sensor@^1.1.9
	links2004/WebSockets@^2.4.0
	bblanchon/ArduinoJson@^6.21.0
	mikalhart/TinyGPSPlus@^1.0.3
build_flags =
	-DCORE_DEBUG_LEVEL=0
